coverage:
  status:
    project:
      default:
        target: 0%      # must be >0% to pass
        threshold: 100% # coverage may drop by up to 100%
    patch:
      default:
        # don't require individual patches to have any particular code coverage
        target: 0%
        threshold: 100%
