[package]
name = "fend"
# Don't forget to update print_version()
version = "0.1.7"
authors = ["printfn <printfn@users.noreply.github.com>"]
description = "Calculator and unit conversion tool"
homepage = "https://github.com/printfn/fend-rs"
repository = "https://github.com/printfn/fend-rs"
readme = "README.md"
license = "MIT"
keywords = ["calculator", "cli", "conversion", "math", "tool"]
edition = "2018"
categories = ["command-line-utilities", "mathematics", "science"]
exclude = ["deploy.sh"]

[dependencies]
rustyline = { version =  "6.2.2", default-features = false, package = "rustyline-with-hint-fix" }
directories = "3.0.1"
ctrlc = "3.1.6"

[dependencies.fend-core]
version = "0.1.7"
path = "./core"

[workspace]
members = ["core", "wasm"]

[profile.release]
lto = true
opt-level = "s" # small code size
