[package]
name = "fend"
version.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme = "../README.md"

[dependencies]
atty = "0.2.14"
console = { version = "0.15.5", default-features = false }
ctrlc = "3.2.4"
fend-core.workspace = true
home = "0.5.4"
nanorand = { version = "0.7.0", default-features = false, features = ["std", "wyrand"] }
rustyline = { version =  "10.1.0", default-features = false, package = "rustyline-with-hint-fix" }
serde = { version = "1.0.152", default-features = false }
toml = "0.7.1"
ureq = { version = "2.6.2", default-features = false, features = ["tls"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["fileapi", "winnt", "errhandlingapi"] }
