[package]
name = "fend"
# Don't bump version numbers manually, use deploy.sh instead
version = "1.0.5"
authors = ["printfn <printfn@users.noreply.github.com>"]
description = "Arbitrary-precision unit-aware calculator"
homepage = "https://github.com/printfn/fend"
repository = "https://github.com/printfn/fend"
readme = "../README.md"
license = "MIT"
keywords = ["calculator", "cli", "conversion", "math", "tool"]
edition = "2021"
categories = ["command-line-utilities", "mathematics", "science"]

[dependencies]
ansi_term = "0.12.1"
atty = "0.2.14"
ctrlc = "3.2.3"
fend-core = { version = "1.0.5", path = "../core" }
home = "0.5.3"
nanorand = { version = "0.6.1", default-features = false, features = ["std", "wyrand"] }
rustyline = { version =  "10.0.1", default-features = false, package = "rustyline-with-hint-fix" }
serde = { version = "1.0.144", default-features = false }
toml = "0.5.9"
