[package]
name = "fend"
version.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme = "../README.md"

[dependencies]
ctrlc = "3.4.4"
fend-core.workspace = true
home = "0.5.9"
native-tls = { version = "0.2.11", optional = true }
rand = { version = "0.8.5", default-features = false, features = ["std", "std_rng"] }
rustyline = { version =  "14.0.0", default-features = false, features = ["with-file-history", "custom-bindings"] }
serde = { version = "1.0.199", default-features = false }
toml = { version = "0.8.12", default-features = false, features = ["parse"] }
ureq = { version = "2.9.7", default-features = false, optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52.0", features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }

[features]
native-tls = [ "dep:ureq", "dep:native-tls", "ureq/native-tls" ]
rustls = [ "dep:ureq", "ureq/tls" ]
default = [ "native-tls" ]
