[package]
name = "fend"
# Don't bump version numbers manually, use deploy.sh instead
version = "0.1.27"
authors = ["printfn <printfn@users.noreply.github.com>"]
description = "Arbitrary-precision unit-aware calculator"
homepage = "https://github.com/printfn/fend"
repository = "https://github.com/printfn/fend"
readme = "README.md"
license = "MIT"
keywords = ["calculator", "cli", "conversion", "math", "tool"]
edition = "2021"
categories = ["command-line-utilities", "mathematics", "science"]

[dependencies]
rustyline = { version =  "9.1.2", default-features = false, package = "rustyline-with-hint-fix" }
directories = "4.0.1"
ctrlc = "3.2.1"
ansi_term = "0.12.1"
toml = "0.5.8"
serde = { version = "1.0.134", features = ["derive"] }
chrono = "0.4.19"
rand = "0.8.4"

[dependencies.fend-core]
version = "0.1.27"
path = "../core"
