[package]
name = "fend-core"
# Don't forget to update html_root_url and get_version()
version = "0.1.3"
authors = ["printfn <printfn@users.noreply.github.com>"]
description = "Backend for calculator and unit conversion tool fend"
homepage = "https://github.com/printfn/fend-rs"
repository = "https://github.com/printfn/fend-rs"
readme = "README.md"
license = "MIT"
keywords = ["calculator", "library", "conversion", "math", "tool"]
edition = "2018"
categories = ["command-line-utilities", "mathematics", "science"]

[features]
default = ["gpl"]

# This enables the GNU Units database in `definitions.units`. If disabled,
# `builtin.units` is used instead.
gpl = []

[dependencies]
