[package]
name = "fend-wasm"
version = "1.0.5"
authors = ["printfn <printfn@users.noreply.github.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/printfn/fend"
description = "Arbitrary-precision unit-aware calculator"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
#default = ["console_error_panic_hook"]
default = []

[dependencies]
fend-core = { path = "../core" }
instant = { version = "0.1.12", features = [ "wasm-bindgen" ] }
js-sys = "0.3.59"
wasm-bindgen = "0.2.82"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz"]
