[package]
name = "fend-wasm"
version = "1.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/printfn/fend"
description = "Arbitrary-precision unit-aware calculator"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
#default = ["console_error_panic_hook"]
default = []

[dependencies]
fend-core = { path = "../core" }
instant = { version = "0.1.12", features = [ "wasm-bindgen" ] }
js-sys = "0.3.60"
wasm-bindgen = "0.2.83"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz"]
