[package]
name = "fend-wasm"
version.workspace = true
# `description`, `homepage`, `repository` and `license` can't be
# from the workspace root due to wasm-pack bug #1180
description = "Arbitrary-precision unit-aware calculator"
edition.workspace = true
homepage = "https://github.com/printfn/fend"
repository = "https://github.com/printfn/fend"
keywords.workspace = true
categories.workspace = true
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
#default = ["console_error_panic_hook"]
default = []

[dependencies]
fend-core.workspace = true
instant = { version = "0.1.12", features = [ "wasm-bindgen" ] }
js-sys = "0.3.61"
wasm-bindgen = "0.2.84"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz"]
