prompt = '> '
enable-colors = false

# change 'C' and 'F' to refer to coulomb and farad
# instead of degrees celsius and degrees fahrenheit
coulomb-and-farad = false

[colors]
number = {}
string = { foreground = 'yellow', bold = true }
identifier = { foreground = 'white' }
keyword = { foreground = 'red', bold = true }
built-in-function = { foreground = 'red', bold = true }
date = {}
other = {}
