name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            artifact-path: target/release/fend
            artifact-platform-name: linux
          - platform: macos-latest
            artifact-path: target/release/fend
            artifact-platform-name: macos
          - platform: windows-latest
            artifact-path: target/release/fend.exe
            artifact-platform-name: windows

    runs-on: ${{ matrix.platform }}

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        rustup update
        cargo build --release --workspace
    - name: Get version
      run: echo "FEND_VERSION=$(cargo run --release -- short-version)" >> $GITHUB_ENV
    - name: Run tests
      run: cargo test --workspace -- --nocapture
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fend-${{ env.FEND_VERSION }}-${{ matrix.artifact-name }}
        path: ${{ matrix.artifact-path }}
        if-no-files-found: error


  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Run clippy
      run: |
        rustup update
        rustup component add clippy
        cargo clippy --workspace --all-targets --all-features -- -D warnings
