name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cargo build --release --workspace
    - name: Run tests
      run: cargo test --workspace
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fend-${{ matrix.platform }}
        path: |
          target/release/fend*
          !target/release/fend.d*
          !target/release/fend.pdb


  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Run clippy
      run: |
        rustup component add clippy
        cargo clippy --all-targets --all-features -- -D warnings
